# Generated by Django 5.2.16 on 2026-07-13 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourierBenchmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier', models.CharField(max_length=50)),
                ('stage', models.CharField(choices=[('pickup_to_dispatch', 'Pickup to Dispatch'), ('dispatch_to_delivery', 'Dispatch to Delivery')], max_length=30)),
                ('expected_hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('courier', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=10)),
                ('order_value', models.IntegerField()),
                ('dispatch_time', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('delivery_attempt_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('rejected', 'Rejected'), ('rto', 'RTO')], max_length=20)),
                ('courier_reported_reason', models.CharField(blank=True, max_length=50, null=True)),
                ('call_log_made', models.BooleanField(blank=True, null=True)),
                ('delay_reason_true', models.CharField(default='none', max_length=50)),
                ('mode', models.CharField(blank=True, max_length=20, null=True)),
                ('monitor_flagged', models.BooleanField(blank=True, null=True)),
                ('monitor_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('diagnosis_verdict', models.CharField(blank=True, max_length=50, null=True)),
                ('diagnosis_confidence', models.FloatField(blank=True, null=True)),
                ('diagnosis_explanation', models.TextField(blank=True, null=True)),
                ('action_taken', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=20)),
                ('output', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trace', to='core.order')),
            ],
        ),
    ]
