# Generated by Django 5.2.16 on 2026-07-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='diagnosis_cause',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
