# Generated by Django 5.2.16 on 2026-07-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_diagnosis_cause'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='action_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
