# Generated by Django 5.2.16 on 2026-07-15 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_action_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='current_hub_arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
