# Generated by Django 5.2.16 on 2026-07-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order_current_hub_arrival_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier', models.CharField(max_length=50, unique=True)),
                ('approved', models.BooleanField(default=False)),
                ('approved_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
