# Generated by Django 5.2.16 on 2026-07-18 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_order_customer_name_order_customer_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineClock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Pipeline Clock',
                'verbose_name_plural': 'Pipeline Clock',
            },
        ),
    ]
